name: school_forum
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
